pages:
  before_script:
      - npm install
      - npm install -g typescript
  script:
      - mkdir .public
      - cp -r * .public
      - mv .public public
      - tsc app.ts
      - mv app.js public
  image: node:latest
  stage: deploy
  artifacts:
    paths:
      - public # art
  only:
    - master
